### ISSUE TITLE
API vs vocabulary for `tag-readout-method` and `manipulation_type`

### ISSUE THREAD

**Issue by bart1** [movebank/movebank-api-doc#16]
I'm retrieving this url: https://www.movebank.org/movebank/service/direct-read?entity_type=deployment&study_id=1259686571

It contains the attribute `tag-readout-method`, in the [vocabulary](http://vocab.nerc.ac.uk/collections/MVB/current/MVB000188/) it says it can be `phone-network` however the api returns me `phone network`. Should dashed be replaced by spaces?

**Comment by bart1** [comment]
@sarahcd: I now found a column that has both a dash and not depending on the study:
``` r
devtools::load_all("~/move2")
#> ℹ Loading move2
curl::curl("https://www.movebank.org/movebank/service/direct-read?entity_type=deployment&study_id=1259686571", handle=movebank_handle()) |> vroom::vroom(show_col_types = F) |> pull("manipulation_type") |> unique()
#> [1] "none"              "manipulated other"
curl::curl("https://www.movebank.org/movebank/service/direct-read?entity_type=deployment&study_id=2943485", handle=movebank_handle()) |> vroom::vroom(show_col_types = F) |> pull("manipulation_type") |> unique()
#> [1] "none"              NA                  "manipulated-other"
```

<sup>Created on 2023-05-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sarahcd** [comment]
Hi Bart, Martin has addressed >90% of cases with invalid controlled list values. All cases where the value could be clearly matched to a valid value (e.g., 'manipulated other' can be confidently corrected to 'manipulated-other') should be compliant now. Hope this helps.

**Comment by bart1** [comment]
Thanks, I now made the `move2` definition match the vocabulary: https://gitlab.com/bartk/move2/-/commit/d9328c93097a55f76a4f83d444c5dd8f97909420

note there are still some strange ones like attachment type that has a space in `fin mount`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000052/ , but I assume `move2` now matchs the definitions
