### ISSUE TITLE
getting names of all available attributes that can be listed in the 'attributes' argument

### ISSUE THREAD

**Issue by annescharf** [movebank/movebank-api-doc#17]
Is there a possibility to get through the API a full list of attributes that the argument `attributes` accepts?

When getting the list of attributes available for a sensor: `https://www.movebank.org/movebank/service/direct-read?entity_type=study_attribute&study_id=2911040&sensor_type_id=653 `

the resulting list:
```
[1] "eobs_battery_voltage"              "eobs_fix_battery_voltage"          "eobs_horizontal_accuracy_estimate"                             
 [4] "eobs_key_bin_checksum"             "eobs_speed_accuracy_estimate"      "eobs_start_timestamp"             
 [7] "eobs_status"                       "eobs_temperature"                  "eobs_type_of_fix"                 
[10] "eobs_used_time_to_get_fix"         "ground_speed"                      "heading"                          
[13] "height_above_ellipsoid"            "location_lat"                      "location_long"                    
[16] "timestamp"                         "update_ts"                         "visible"     
```
seems incomplete when looking at the example of the API:

`https://www.movebank.org/movebank/service/direct-read?entity_type=event&study_id=2911040&attributes=individual_local_identifier,tag_local_identifier,timestamp,location_long,location_lat,visible,individual_taxon_canonical_name`

as `individual_local_identifier,tag_local_identifier,individual_taxon_canonical_name` are not included in the `study_attributes` table.

Now, ok, one could think that also animal, tag, deployment attributes can be listed in the `attributes` argument, but if you search for which are available with e.g. `entity_type=individual`, than these attributes are called `local_identifier,taxon_canonical_name`. Very confusing for most of the users.
Is there a way of getting the complete list, with the correct names, that the `attributes` argument accepts? Because as soon as there is one wrong, the study won't download....

Thanks!!

**Comment by sarahcd** [comment]
I understand the confusion! While this does not necessarily resolve all issues, below are two clarifications to be aware of. Could you have a look and let me know 1) if this resolves the issues for the current use case and (2) if this modifies any of your previous API requests that we compiled a few months ago?

1. When coping with events distinguish between event-level attributes and event-set-level attributes.

2. The concept of attribute aliases

Requests for entity_type=study_attribute return all event-level attributes specific for that study/sensor-type. Event-set-level attributes are not included, they are the same for all studies.

The attributes id and local_identifier exist in both tag and individual. It is therefore necessary to use aliases (e.g. local_identifier -> tag_local_identifier) for those attributes when using them as event-set-level attributes for event queries.

As opposed to study event-level attributes, the event-set-level attributes don't change over time. You could just keep them in a list etc. They are:

individual_id, deployment_id, tag_id, study_id, sensor_type_id, individual_local_identifier, tag_local_identifier, individual_taxon_canonical_name

For completeness, there is a third type of attributes: summary attributes. They can be used to generate summaries for individuals and tags:

number_of_events, timestamp_end, timestamp_start

Example: https://www.movebank.org/movebank/service/direct-read?entity_type=individual&study_id=2911040&attributes=id,local_identifier,marker_id,nick_name,number_of_events,sensor_type_ids,sex,study_id,taxon_canonical_name,timestamp_end,timestamp_start

**Comment by annescharf** [comment]
Thanks @sarahcd, I'll try to make it clear in the help file of the download function in `move2` to reduce confusion as much as possible

**Comment by annescharf** [comment]
@sarahcd I think we fund a solution to avoid confusion. But I think that it would be very helpful if the explanation above was included somewhere in the API documentation :-)

**Comment by sarahcd** [comment]
I added some clarifications in movebank-api.md
