### ISSUE TITLE
Argos Doppler shift not producing sensor datatable

### ISSUE THREAD

**Issue by coverton-usgs** [movebank/movebank-api-doc#18]
I just ran into an issue using package 'move' when trying to get the reference data for one of my studies.  I was able to traceback the error to a 0 record sensor data.  Specifically, 

`https://www.movebank.org/movebank/service/direct-read?entity_type=sensor&tag_study_id=28243149185`

produces no records.  I get the 3 column headings 'id', 'sensor_type_id', and 'tag_id' but no rows.
but my companion project with GPS sensors

`https://www.movebank.org/movebank/service/direct-read?entity_type=sensor&tag_study_id=2681479653`

does work, for this study I get rows for each of the 40 tags.

Since there are no records output, it is causing an error in the 'move' package, but it seems like there should be 5 records for this project - one for each tag.

**Comment by sarahcd** [comment]
Hi Cory, could you send a screenshot of the study details from study 28243149185 to support(at)movebank.org?
https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study28243149185

I have no access to view the study so can't give any insight on the expected result.

**Comment by sarahcd** [comment]
No worries, glad that was an easy fix
