### ISSUE TITLE
animal-nickname not listed in documentation

### ISSUE THREAD

**Issue by peterdesmet** [movebank/movebank-api-doc#5]
> @sarahcd Not sure if this is the right place to log data _upload_ issues, but I wanted to document it none the less.

I noticed that one can populate the metadata field `Nickname`. Indeed, if you include the field `animal-nickname` in a metadata csv upload, it is automatically recognized.

The term however is not documented in https://www.movebank.org/node/2381 or the Movebank reference data template.

**Comment by bart1** [comment]
I just noticed this is a more common issue for example for this api request `https://www.movebank.org/movebank/service/direct-read?entity_type=individual&study_id=1259686571` the following columns are returned: `comments death_comments earliest_date_born exact_date_of_birth id latest_date_born local_identifier nick_name ring_id sex taxon_canonical_name timestamp_start timestamp_end number_of_events number_of_deployments sensor_type_ids taxon_detail`. For many terms they seem to be defined in the documentation as `animal_` (e.g. sex, taxon_detail, ring_id and nick_name). However the api returns them without the animal term assosicated

**Comment by bart1** [comment]
Thanks for the update @sarahcd , is there a way to see the changes in the vocabulary? As some might have consequences for `move2`

**Comment by sarahcd** [comment]
there is a separate URI with the date of each version of each attribute at http://vocab.nerc.ac.uk/collection/MVB/current/
